version: '3'

networks:
  backend:

services:

  web:
    
    image: nginx:stable-alpine
    container_name: web
    ports:
      - 80:80
    volumes:
      - .:/wkspace/app
      - ./tools/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf

    depends_on:
      - php
    networks:
      - backend

  php:
    build:
      context: ./tools/php
      dockerfile: Dockerfile

    container_name: php
    volumes:
      - .:/wkspace/app

    networks:
      - backend